sudo: false
language: ruby
cache: bundler
rvm: 2.6.0

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production

install:
  - bundle install
  - bundle update

script:
  - bundle exec rake site:deploy[_config.yml] 
  - bundle exec rake site:deploy[_config.fii.yml]
