# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# Build Settings
markdown: kramdown
permalink: pretty
exclude:
  - CONTRIBUTING
  - CONTRIBUTORS
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .gitignore
  - .travis.yml

# Enable minification SASS
sass:
  style: compressed

# Site Settings
url: "https://teaching.alexcoman.com"
baseurl: ""
force-https: True
google-tracking-id: ""
lang: "ro"

favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"
me-img: "/img/jetpacktocat.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: ""

syntax-highlight: True
email: "contact@alexcoman.com"
404-img: "/img/labtocat.png"
paginate_path: "blog/page:num/"

# Settings for deploy rake task
username:        "alexandrucoman"
repo:            "teaching.alexcoman.com"
branch:          "master"
relative_source: "../teaching.alexcoman.com/"
destination:     "../teaching.alexcoman.com-pages/"
production_url:  "http://teaching.alexcoman.com/"
source_url:      "https://github.com/alexandrucoman/teaching.alexcoman.com"
