title: "Alexandru Coman"
author: "Alex Coman"
meta:

homepage:
  terminal:
    - name: "~ $ whoami"
      output: >
        <a href="https://alexcoman.com" target="_blank"
          title="Situl personal al lui Alexandru Coman">Alexandru Coman</a><br>
        e-mail: <a href="mailto:Alexandru Coman <alex.coman@info.uaic.ro>">alex.coman@info.uaic.ro</a><br>
        url: <a href="https://profs.info.uaic.ro/~alex.coman/">profs.info.uaic.ro/~alex.coman/</a>

    - name: "~ $ tree -d teach"
      output: |
        teach<br>
        ├── courses<br>
        │   └── <a href="teach/courses/open-source">Metodologii de lucru în mediul Open Source</a><br>
        └── labs<br>
        &nbsp;&nbsp;&nbsp;&nbsp;├── <a href="teach/courses/web">Tehnologii Web</a><br>
        &nbsp;&nbsp;&nbsp;&nbsp;└── <a href="teach/courses/open-source">Metodologii de lucru în mediul Open Source</a><br>
    
    - name: "~ $ tree -d resurse"
      output: >
        <a href="resurse/">Resurse</a><br>
        ├── <a href="resurse/noutati">Noutăți</a><br>
        └── <a href="resurse/tutorial">Tutorial</a><br>
