author: "Alex Coman"
title: "Laboratoare @FII"
meta:
    - name: "description"
      lang: "ro"
      content: "Situl dedicat laboratoarelor susținute în cadrul Facultății de Informatică din Iași."

    - name: "keywords"
      lang: "en"
      content: >
        Web, WWW, technology, course, Romania, Iasi, Computer Science, university,
        academic, information, education, school, project, lang programming,
        document, software, application, student, grade

    - name: "keywords"
      lang: "ro"
      content: >
        Web, WWW, technologie, curs, Romania, Iasi, Informatica, universitate,
        academic, informatie, educatie, scoala, proiect, limbaj, programare,
        document, software, aplicatie, student, nota
header:
  title: 'Laboratoare'
  subtitle: '@FII'
  icon: fas fa-laptop
  tagline: []
