title: "{ Alex Coman }"
links:
  - section: "about"
    text: "Despre"

  - link: "/web"
    text: "Tehnologii Web"

  - link: "/resurse"
    text: "Resurse"

  - section: "contact"
    text: "Contact"
