author: "Alex Coman"
title: "Resurse disponibile"
meta:
    - name: "description"
      lang: "ro"
      content: "Resurse disponibile pentru stundeții ce urmează cursurile prezentate în acest sit."

    - name: "keywords"
      lang: "en"
      content: >
        Web, WWW, technology, course, Romania, Iasi, Computer Science, university,
        academic, information, education, school, project, lang, programming,
        document, software, application, student, grade

    - name: "keywords"
      lang: "ro"
      content: >
        Web, WWW, technologie, curs, România, Iași, informatică, universitate,
        academic, informație, educație, școală, proiect, limbaj, programare,
        document, software, aplicație, student, notă
header:
  title: 'Resurse'
  subtitle: 'disponibile'
  icon: 'fas fa-code-branch'
  tagline: []
