author: "Alex Coman"
title: "Open Source"
meta:
    - name: "description"
      lang: "ro"
      content: "Situl dedicat materiei Metodologii de lucru în mediul Open-Source"

    - name: "keywords"
      lang: "en"
      content: >
        Web, WWW, technology, course, Romania, Iasi, Computer Science, university,
        academic, information, education, school, project, lang, programming,
        document, software, application, student, grade

    - name: "keywords"
      lang: "ro"
      content: >
        Web, WWW, technologie, curs, România, Iași, informatică, universitate,
        academic, informație, educație, școală, proiect, limbaj, programare,
        document, software, aplicație, student, notă
header:
  title: 'Open'
  subtitle: 'Source'
  icon: fas fa-book
  tagline: []
